# -*-makefile-*-

CURR_DIR = $(shell pwd)
SPACE := $(subst ,, )
GAE_LIB_PATHS := $(shell ls -d $(GAE_HOME)/lib/* | sort -r)
GAE_LIBS := $(subst $(SPACE),:,$(GAE_LIB_PATHS))

test ::
	@export PYTHONPATH=$(PYTHONPATH):$(GAE_HOME):$(GAE_LIBS) ; \
	$(PARENTD_TOOLS)/pytester.py --TEST_DIR=$(CURR_DIR)

